GitHub Actions Workflow (#2)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -16,11 +16,12 @@ jobs:
   ci:
     name: Test Ansible provisioning
     runs-on: macos-latest
+    env:
+      INVENTORY: work
     steps:
-      - run: |
-          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
-          echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
-          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
+      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
+      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
+      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
 
       - name: Check out repository code
         uses: actions/checkout@v4
@@ -28,13 +29,28 @@ jobs:
       - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
       - run: echo "🖥️ The workflow is now ready to test your code on the runner."
 
-      - name: List files in the repository
+      - name: Install Ansible
+        run: brew install ansible
+
+      - run: ansible --version
+
+      - name: Verify the playbook's syntax
+        run: ansible-playbook --inventory ${INVENTORY} --syntax-check site.yml
+
+      - name: Test the playbook
+        run: ansible-playbook --inventory ${INVENTORY} site.yml
+
+      - name: Test the playbook's idempotence
         run: |
-          ls ${{ github.workspace }}
+          output=$(mktemp)
+          ansible-playbook --inventory ${INVENTORY} site.yml | tee ${output}
+
+          # anything_changed=$(tail ${output} | grep -q 'changed=0.*failed=0')
+          # if [[ "${anything_changed}" -gt 0 ]]; then
+          #   echo "Playbook not idempotent!" >> $GITHUB_OUTPUT
+          #   # TODO fix up playbook
+          #   # exit 1
+          # fi;
 
       - run: echo "🍏 This job's status is ${{ job.status }}."
 
-      # - name: Check Syntax
-
-      # test-installation:
-      # test-idempotence:
